#:schema node_modules/wrangler/config-schema.json
name = "cordinova"
main = ".open-next/worker.js"
compatibility_date = "2026-04-16"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".worker-next"

[assets]
directory = ".open-next/assets"

[observability]
enabled = true